spring.application.name=comercio
spring.datasource.url=jdbc:postgresql://localhost:5432/lojas_belem
spring.datasource.username=postgres
spring.datasource.password=54321

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


resend.api.key=re_52NHrRnX_79C4BNAhr41b5Ho5RSvpkHSs